name: Auto Bump Tailwind Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Tailwind CSS version to upgrade to'
        required: true
        type: string
        default: 'latest'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update Tailwind CSS version
        run: |
          if [ "${{ github.event.inputs.version }}" = "latest" ]; then
            npm install tailwindcss@latest
          else
            npm install tailwindcss@${{ github.event.inputs.version }}
          fi

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump Tailwind CSS to version ${{ github.event.inputs.version }}"
          title: "chore: bump Tailwind CSS to version ${{ github.event.inputs.version }}"
          body: |
            This PR automatically bumps the Tailwind CSS version to ${{ github.event.inputs.version }}.
            
            Changes made:
            - Updated Tailwind CSS package version
            - Updated package-lock.json

      - name: Output PR URL
        run: |
          PR_NUMBER=${{ steps.create-pull-request.outputs.pull-request-number }}
          PR_URL="https://github.com/${{ github.repository }}/pull/$PR_NUMBER"
          echo "Pull Request created at $PR_URL"

permissions:
  contents: write
  pull-requests: write 