name: Update Tailwind Version Options

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update workflow versions
        run: node scripts/update-workflow-versions.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Tailwind version options"
          title: "chore: update Tailwind version options"
          body: |
            This PR automatically updates the available Tailwind CSS versions in the workflow.
            
            Changes made:
            - Updated version options in the workflow file

      - name: Output PR URL
        run: echo "Pull Request created at ${{ steps.create-pull-request.outputs.pull-request-url }}" 